### ISSUE TITLE
Post parameters with multiple values.

### ISSUE THREAD

**Issue by wgehalo** [SamDecrock/node-httpreq#25]
Hello,
I'm wondering if there's a way to assign multiple values to POST parameters. I'm working with a server that requires this formatting.

I've tried the following:
`    parameters: {
        ajaxfunc: 'ajax_writemodule',
        ajaxretfunc: 'writemodule',
        ajaxrnd: new Date().getTime(),
        ajaxargs: ['editmanufacturingnotes', 'manufacturingnotesmod', '31110', 'THIS IS A TEST']
    }`

It doesn't work. I've captured the form data and this is the raw information:
`'ajaxfunc=ajax_writemodule&ajaxretfunc=writemodule&ajaxrnd=1477430594267&ajaxargs[]=editmanufacturingnotes&ajaxargs[]=manufacturingnotesmod&ajaxargs[]=31110&ajaxargs[]=THIS IS A TEST'`

I can't add the brackets after the ajaxargs parameter. Is there a way to use the raw form data with this library?

**Comment by fvdm** [comment]
You can send a raw data string by using the `body` property instead of `parameters`. Make sure to properly urlencode it and set the Content-Type header.

Because of the brackets I assume the endpoint is using PHP, then it enumerates the keys in an array. Have you tried to insert a number between the brackets? Like this:

```js
parameters: {
  ajaxfunc: 'ajax_writemodule',
  ajaxretfunc: 'writemodule',
  ajaxrnd: new Date().getTime(),
  'ajaxargs[0]': 'editmanufacturingnotes',
  'ajaxargs[1]': 'manufacturingnotesmod',
  'ajaxargs[2]': '31110',
  'ajaxargs[3]': 'THIS IS A TEST'
}
```

Note how the keys are wrapped in quotes.

**Comment by wgehalo** [comment]
Well hot damn that worked! Thanks so much fvdm!

**Comment by fvdm** [comment]
You're welcome, have a nice day!
